name: ContentMakers
main: ru.progrm_jarvis.contentmakers.ContentMakersPlugin
version: 0.1-Beta
author: PROgrm_JARvis (JARvis (Пётр) PROgrammer)
softdepend: [PlaceholderAPI]
commands:
  stream:
    description: 'I am a command to get some fun :)'